# Generated by Django 4.2.2 on 2023-07-04 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_remove_employee_salary_employee_date_hired_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-due_date'], 'verbose_name': 'debt', 'verbose_name_plural': 'debts'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name'], 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeexpense',
            options={'ordering': ['-date'], 'verbose_name': 'employee expense', 'verbose_name_plural': 'employee expenses'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'sale', 'verbose_name_plural': 'sales'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('CU', 'Customer'), ('PR', 'Provider')], help_text='Select the category of the contact.', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(help_text='Enter the name of the contact.', max_length=200),
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the amount of the debt.', max_digits=6, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='date',
            field=models.DateField(help_text='Enter the date of the debt.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(help_text='Enter the due date of the debt.', verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='product',
            field=models.ForeignKey(help_text='Select the product associated with the debt.', on_delete=django.db.models.deletion.CASCADE, to='invoice_app.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='provider',
            field=models.ForeignKey(help_text='Select the provider associated with the debt.', limit_choices_to={'category': 'PR'}, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.contact', verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(help_text='Enter the date when the employee was hired.', verbose_name='Date Hired'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_terminated',
            field=models.DateField(blank=True, help_text='Enter the date when the employee was terminated, if applicable.', null=True, verbose_name='Date Terminated'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Enter the name of the employee.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wage',
            field=models.DecimalField(decimal_places=2, help_text='Enter the wage/salary of the employee.', max_digits=10, verbose_name='Wage'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the amount of the expense.', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='date',
            field=models.DateField(help_text='Enter the date of the expense.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='description',
            field=models.CharField(help_text='Enter a description of the expense.', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='employeeexpense',
            name='employee',
            field=models.ForeignKey(help_text='Select the employee associated with the expense.', on_delete=django.db.models.deletion.CASCADE, to='invoice_app.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the product.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The price of the product.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(help_text='Select the customer for the sale.', limit_choices_to={'category': 'CU'}, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.contact', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(help_text='Enter the date of the sale.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(help_text='Select the product for the sale.', on_delete=django.db.models.deletion.CASCADE, to='invoice_app.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter the quantity sold.', verbose_name='Quantity'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['product'], name='debt_product_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeexpense',
            index=models.Index(fields=['employee'], name='employee_expense_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['product'], name='sale_product_idx'),
        ),
    ]
