# Generated by Django 4.2.2 on 2023-07-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_alter_contact_options_alter_debt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(help_text='Enter the date of the transaction.', verbose_name='Transaction Date')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash'), ('transfer', 'Transfer')], help_text='Select the payment method for the transaction.', max_length=20, verbose_name='Payment Method')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='draft', help_text='Select the status of the invoice.', max_length=20, verbose_name='Status')),
                ('transaction_number', models.CharField(blank=True, help_text='Unique transaction number.', max_length=50, unique=True, verbose_name='Transaction Number')),
                ('contact', models.ForeignKey(help_text='Select the contact associated with the transaction.', on_delete=django.db.models.deletion.CASCADE, to='invoice_app.contact', verbose_name='Contact')),
                ('employee', models.ForeignKey(help_text='Select the employee associated with the transaction.', on_delete=django.db.models.deletion.CASCADE, to='invoice_app.employee', verbose_name='Employee')),
                ('sales', models.ManyToManyField(help_text='Select the sales associated with the invoice.', to='invoice_app.sale', verbose_name='Sales')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
