version: "3.8"
services:
  web:
    build: .
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "python",
        "/src/manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  postgres_data:
