# Generated by Django 4.2.4 on 2023-08-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_customuser_managers'),
        ('business', '0003_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.company'),
            preserve_default=False,
        ),
    ]
